
insert into MOVIES (ID, TITLE, SUMMARY, DIRECTORS, ACTORS, RUNNING_TIME, POSTER_LINK, TRAILER_LINK) values (1, 'Avengers: Endgame', 'After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos'' actions and restore balance to the universe.', 'Anthony Russo, Joe Russo', 'Robert Downey Jr., Chris Evans, Mark Ruffalo', 182, 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_.jpg', 'https://www.youtube.com/embed/TcMBFSGVi1c');
insert into MOVIES (ID, TITLE, SUMMARY, DIRECTORS, ACTORS, RUNNING_TIME, POSTER_LINK, TRAILER_LINK) values (2, 'Raya and the Last Dragon', 'In a realm known as Kumandra, a re-imagined Earth inhabited by an ancient civilization, a warrior named Raya is determined to find the last dragon.', 'Don Hall, Carlos López Estrada', 'Kelly Marie Tran, Awkwafina, Gemma Chan', 107, 'https://mlpnk72yciwc.i.optimole.com/cqhiHLc.WqA8~2eefa/w:auto/h:auto/q:75/https://bleedingcool.com/wp-content/uploads/2021/01/LARE_BS_75.10_v3.0_BusShelter_Mech9.jpg', 'https://www.youtube.com/embed/1VIZ89FEjYI');
insert into MOVIES (ID, TITLE, SUMMARY, DIRECTORS, ACTORS, RUNNING_TIME, POSTER_LINK, TRAILER_LINK) values (3, 'Soul', 'After landing the gig of a lifetime, a New York jazz pianist suddenly finds himself trapped in a strange land between Earth and the afterlife.', 'Pete Docter, Kemp Powers', 'Jamie Foxx, Tina Fey, Graham Norton', 100, 'https://i.ytimg.com/vi/EVB21AxR1Hw/movieposter_en.jpg', 'https://www.youtube.com/embed/xOsLIiBStEs');
insert into MOVIES (ID, TITLE, SUMMARY, DIRECTORS, ACTORS, RUNNING_TIME, POSTER_LINK, TRAILER_LINK) values (4, 'Crazy Rich Asians', 'This contemporary romantic comedy, based on a global bestseller, follows native New Yorker Rachel Chu to Singapore to meet her boyfriend''s family.', 'Jon M. Chu', 'Constance Wu, Henry Golding, Michelle Yeoh', 120, 'https://m.media-amazon.com/images/M/MV5BMTYxNDMyOTAxN15BMl5BanBnXkFtZTgwMDg1ODYzNTM@._V1_.jpg', 'https://www.youtube.com/embed/14ZHRBfpeNg');

insert into CINEMAS (ID, MAX_ROW, MAX_COLUMN) values (1, 9, 9);
insert into CINEMAS (ID, MAX_ROW, MAX_COLUMN) values (2, 10, 8);
insert into CINEMAS (ID, MAX_ROW, MAX_COLUMN) values (3, 3, 7);

insert into MOVIE_SCREENINGS (ID, MOVIE_ID, CINEMA_ID, SCHEDULE_DATE, SCHEDULE_TIME) values (1, 1, 1, '2021-05-24', '10:15:00.000');
insert into MOVIE_SCREENINGS (ID, MOVIE_ID, CINEMA_ID, SCHEDULE_DATE, SCHEDULE_TIME) values (2, 1, 1, '2021-05-24', '12:15:00.000');
insert into MOVIE_SCREENINGS (ID, MOVIE_ID, CINEMA_ID, SCHEDULE_DATE, SCHEDULE_TIME) values (3, 2, 1, '2021-05-23', '17:00:00.000');
insert into MOVIE_SCREENINGS (ID, MOVIE_ID, CINEMA_ID, SCHEDULE_DATE, SCHEDULE_TIME) values (4, 3, 2, '2021-05-23', '11:00:00.000');
insert into MOVIE_SCREENINGS (ID, MOVIE_ID, CINEMA_ID, SCHEDULE_DATE, SCHEDULE_TIME) values (5, 3, 2, '2021-05-23', '15:00:00.000');
insert into MOVIE_SCREENINGS (ID, MOVIE_ID, CINEMA_ID, SCHEDULE_DATE, SCHEDULE_TIME) values (6, 3, 3, '2021-05-25', '16:00:00.000');
insert into MOVIE_SCREENINGS (ID, MOVIE_ID, CINEMA_ID, SCHEDULE_DATE, SCHEDULE_TIME) values (7, 3, 3, '2021-05-25', '11:00:00.000');

insert into SEATS (ROW, COLUMN, CINEMA_ID) values (1, 1, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (1, 2, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (1, 3, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (1, 4, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (1, 6, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (1, 7, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (1, 8, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (1, 9, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (2, 1, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (2, 2, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (2, 3, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (2, 4, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (2, 6, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (2, 7, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (2, 8, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (2, 9, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (3, 1, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (3, 2, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (3, 3, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (3, 4, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (3, 6, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (3, 7, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (3, 8, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (3, 9, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (5, 1, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (5, 2, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (5, 3, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (5, 4, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (5, 6, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (5, 7, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (5, 8, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (5, 9, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (7, 1, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (7, 2, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (7, 3, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (7, 4, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (7, 6, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (7, 7, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (7, 8, 1);
insert into SEATS (ROW, COLUMN, CINEMA_ID) values (7, 9, 1);